---
abstract: 'BalancedPayments API bindings'
author:
  - 'Khaled Hussein <khaled.hussein@gmail.com>'
  - 'Naveed Massjouni <naveedm9@gmail.com>'
  - 'Will Wolf<throughnothing@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  HTTP::Response: 0
  Test::Mock::LWP::Dispatch: 0
  Test::More: 0
  Test::Most: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-BalancedPayments
requires:
  Carp: 0
  HTTP::Request::Common: 0
  JSON: 0
  LWP::UserAgent: 0
  Moose: 0
  Moose::Role: 0
version: 0.1100
